=== Elifabet/IFCD0210/MF0491-3 cliente/UF1841/E2/altovapractica1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generado con XMLSpy v2019 rel. 3 sp1 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ciudad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Las Palmas de Gran Canaria"/>
				<xs:enumeration value="S7c de Tenerife"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="entrenador">
		<xs:complexType>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="ciudad"/>
				<xs:element ref="entrenador"/>
				<xs:element ref="jugadores"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipos_de_futbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugador">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="nacionalidad"/>
			</xs:sequence>
			<xs:attribute name="posicion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="delantero"/>
						<xs:enumeration value="portero"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="jugadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="jugador" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nacionalidad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="argentino"/>
				<xs:enumeration value="española"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Dani Hernandez"/>
				<xs:enumeration value="Fernando Coniglio"/>
				<xs:enumeration value="Las Palmas"/>
				<xs:enumeration value="Rafa Mir"/>
				<xs:enumeration value="Raúl Fernández-Cavada"/>
				<xs:enumeration value="Tenerife"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Elifabet/IFCD0210/MF0491-3 cliente/UF1841/E2/altovapractica1.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos_de_futbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/IFCD0210/MF0491-3%20cliente/UF1841/E2/altovapractica1.xsd">
	<equipo>
		<nombre>Tenerife</nombre>
		<ciudad>S7c de Tenerife</ciudad>
		<entrenador/>
		<jugadores>
			<jugador posicion="portero">
				<nombre>Dani Hernandez</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Fernando Coniglio</nombre>
				<nacionalidad>argentino</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
	<equipo>
		<nombre>Las Palmas</nombre>
		<ciudad>Las Palmas de Gran Canaria</ciudad>
		<entrenador/>
		<jugadores>
			<jugador posicion="portero">
				<nombre>Raúl Fernández-Cavada</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Rafa Mir</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
</equipos_de_futbol>
